# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9234a2824835a816e12686db8ddcada79b6a9d3b8aa4e3cc196997a38c04cc2c24edcb1d3aefc4a6a14d53d664f89408b5d455f88f6360e2d2659713bb28d667

test:
  secret_key_base: 6e78b506eb5072b8fe238d58af8868dbb6f42ac72ff830cc8b6e27d6a758c00286647e4c9bb1ef790cfcb3b119489f42dfe2e39633e6ff970888f608e7e865d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
